include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_override_of_non_virtual_member: warning
    todo: ignore

linter:
  rules:
    always_use_package_imports: true
    prefer_relative_imports: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true

